#!/bin/bash
PIPE="$HOME/.pomodoro/xmobar"

STATE=$1
TICK=$2
TOTAL=$3

function repeat() {
    printf '%*s' "$2" | tr ' ' "$1"
}

function message() {
    bars=$(repeat '#' "$TICK")
    case "$STATE" in
        "Pomodoro")
            SHORT_STATE="P"
            ;;
        "Break")
            SHORT_STATE="B"
            ;;
        *)
            SHORT_STATE="?"
            ;;
    esac
    printf "%s |%-*s|\n" "$SHORT_STATE" "$TOTAL" "$bars"
}

message >> "$PIPE"
