#!/bin/bash
PIPE="$HOME/.pomodoro/xmobar"

STATE=$1
TICK=$2
TOTAL=$3

function repeat() {
    printf '%*s' "$2" | tr ' ' "$1"
}

function message() {
    bars=$(repeat '#' "$TICK")
    case "$STATE" in
        "Pomodoro")
            SHORT_STATE="P"
            COLOR="#268bd2"
            ;;
        "Break")
            SHORT_STATE="B"
            COLOR="#859900"
            ;;
        *)
            SHORT_STATE="?"
            COLOR="#dc322f"
            ;;
    esac
    printf "<fc=$COLOR>%s |%-*s|</fc>\n" "$SHORT_STATE" "$TOTAL" "$bars"
}

message >> "$PIPE"
