#!/bin/bash
STATE=$1
TICK=$2
TOTAL=$3

function repeat() {
    printf '%*s' "$2" | tr ' ' "$1"
}

bars=$(repeat '#' "$TICK")
printf "%s: |%-*s| %02d/%02d\r" "$STATE" "$TOTAL" "$bars" "$TICK" "$TOTAL"
