#!/bin/bash
PIPE=$HOME/.pomodoro/xmobar

SCRIPTPATH=$(dirname "$0")
SCRIPTPATH=$( (cd "$SCRIPTPATH" && pwd) )

message=$(sh "$SCRIPTPATH"/progressbar "$1" "$2" "$3" | tr '\r' ' ')
echo "$message" >> "$PIPE"
